### ISSUE TITLE
Hardcoded path in interpreter

### ISSUE THREAD

**Issue by SheatNoisette** [nickmqb/muon#1]
The path for Muon compiler files in the bootstrap interpreter are hardcoded to `D:/muon`. Moreover, it's an absolute path.

Maybe try changing it to an relative path and/or add a custom argument in Main which can provide a custom path ?

**Comment by nickmqb** [comment]
Good idea! Fixed in: d557c18d2dcd3fc15a7a7a6ed6dbfa0fc76f400b

A quick word of caution. The C# interpreter only serves to build the compiler, and has many hacks. Here be dragon's and all that ;).
