### ISSUE TITLE
IAllocator.free question

### ISSUE THREAD

**Issue by mna** [nickmqb/muon#23]
I noticed that the `IAllocator` implements the `free` function, but currently, the `freeFn` is never set in any allocator (not even in `heapAllocator`), so there is no way to free up memory.

Is there a reason for this (other than "not ready yet" of course, totally valid)? Patching the allocator manually seems to work for me (couldn't run `valgrind` to validate as I'm on mac ATM):

```
free(ptr pointer) void #Foreign("free")

freeFn(data pointer, ptr pointer) {
  assert(ptr != null)
  free(ptr)
}

main() {
  alloc := Memory.heapAllocator()
  alloc.freeFn = freeFn
  ::currentAllocator = alloc

  intPtr := new 456
  printf("intPtr: %d\n", intPtr^)
  raw := pointer_cast(intPtr, pointer)
  ::currentAllocator.free(raw)
}
```

Is there any plan to add a language mechanism (such as `defer` or something else) to make the free call  close to the allocation?

Thanks,
Martin

**Comment by nickmqb** [comment]
No other reason than "did't get around to it yet", but it definitely makes sense to add it! I've just added it to the standard library here: https://github.com/nickmqb/muon/commit/e3ebc7a4465069d530d335d4994aef00f2773bbf

A defer statement is planned. However, keep in mind that Muon does not have exceptions/stack unwinding. defer will just be syntactic sugar for defining code to be run prior to function (or block) exit.
