### ISSUE TITLE
Match / switch and array literal question

### ISSUE THREAD

**Issue by mna** [nickmqb/muon#24]
Hello,

I'm doing the advent of code in muon for fun, and I ran in a couple of syntax/language issues that may be just that I don't know how to do it properly or that are unavailable at the moment but planned for the future.

The `match` statement appears to work only to "inspect" a tagged pointer, not like a versatile switch statement (i.e. I wanted to "switch" on an integer instead of `if...else if...else`, here: https://github.com/mna/advent02/blob/master/main.mu#L99). Is that correct that there is no `match` support (nor `switch`) for that use-case at the moment?

The second point is that I wanted to initialize an array with some compile-time values, but couldn't find the syntax to do so (I ended up implementing a string-to-array-int function: https://github.com/mna/advent02/blob/master/main.mu#L72). Is there a way to do this at the moment? I guess if not you'll certainly support some syntax to do this in the future?

Thanks!
Martin

**Comment by nickmqb** [comment]
Hi, you're correct, neither are available at the moment but both features are planned. For `match`, I'm also considering adding `match` expressions, e.g. `x := match cond { ... }`. Compile time initialization of arrays will most likely look like `a := Array [1, 2, 3]` and I'd like to support all core containers (i.e. Array, List, Set and Map). FYI, this is the current roadmap: https://github.com/nickmqb/muon/blob/master/docs/roadmap.md (you made me realize it wasn't completely up to date so I've just updated it)

**Comment by mna** [comment]
Awesome, great idea for match expressions! Thanks, sorry I didn't think about checking the roadmap.

**Comment by nickmqb** [comment]
No worries, happy to help! Once advent of code is over, would you be willing to write up a quick summary of your experience with Muon? I'd be interested in hearing feedback from early adopters like yourself.

**Comment by mna** [comment]
Sure! Note that I will try various new-ish languages throughout the calendar (I've done today's with `odin`), but yeah I'll be happy to share my thoughts about this.

**Comment by nickmqb** [comment]
Thanks! Ah I see, it should be interesting to compare the various strengths of these languages.
