### ISSUE TITLE
Mirror in GitLab

### ISSUE THREAD

**Issue by danimesq** [nickmqb/muon#28]

**Comment by danimesq** [comment]
https://gitlab.com/muonlang
@nickmqb I could invite if you have a GitLab account.

**Comment by nickmqb** [comment]
I'd like to keep things as simple as possible. It's a bit too early to set up mirrors I think. For now, can you grant me access to the GitLab org so I can set things up at a later time? I've just signed up for GitLab, my handle is the same as here: nickmqb

**Comment by nickmqb** [comment]
I've received and accepted your invite.
