### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by danimesq** [nickmqb/muon#29]
- [ ] muonlang.github.io
- [ ] muonlang.gitlab.io

**Comment by nickmqb** [comment]
I haven't fully figured out what I want to do with the Muon development blog yet. I may use it for the occasional non-Muon related post. So for now, we should leave it at its current url. Going to close this for now, we can re-evaluate at a future time.

**Comment by danimesq** [comment]
Using a front site for this is so important as having a README.md.
I suggest creating a simple texty site, and name its repo as muonlang.github.io

**Comment by nickmqb** [comment]
I agree that further down the road we probably want to do this. But for now, I'd like to keep things as simple as possible and use a single "landing page" (i.e. the README).
