### ISSUE TITLE
Are there any memory leaks?

### ISSUE THREAD

**Issue by haifenghuang** [nickmqb/muon#33]
First, I think the `muon` is very impressive. But I have one doubt:

```
   Are there any memory leaks regarding the generated '.c' file?
```

**Comment by nickmqb** [comment]
Thank you.

In Muon, memory management is the responsibility of the programmer.

In some cases, memory leaks are OK. For example, the Muon compiler itself does not free memory, but this is fine: the compiler only runs for a short time, then the OS simply cleans up all the memory on process exit.

In other cases, memory leaks are not OK. For example, in games that need to run for a longer time. https://github.com/nickmqb/big2 is a good example. There are no memory leaks in this program. After each frame, memory is freed. Have a look at how `::currentAllocator` is set, `RingAllocator`, `freeUpToMarker`, and `FixedCapList` to see how this is done. This is just an example though, there are many other possible ways to manage memory; Muon's philosophy is to leave it up to the programmer to pick the best approach for the task at hand.

Hope that helps! Closing this issue, but feel free to re-open if you have questions.
