### ISSUE TITLE
Example won't build

### ISSUE THREAD

**Issue by jindorx** [nickmqb/muon#35]
Bootstrap compiler builds fine, but examples won't:
```
~/packages/muon-master/examples$ uname -ms
Linux x86_64
~/packages/muon-master$ cd bootstrap/
~/packages/muon-master/bootstrap$ gcc -O3 -o mu mu.c
~/packages/muon-master/bootstrap$ cd ../examples/
~/packages/muon-master/examples$ ../bootstrap/mu ../lib/core.mu hello_world.mu --output-file hello_world.c
Fatal: missing declaration of core type bool32
1 errors
```
FYI, make in the root directory doesn't work either. Maybe not up-to-date with the transition to 64-bit version? 

```
~/packages/muon-master/examples$ cd ..
~/packages/muon-master$ make
gcc -m32 -O3 -o bootstrap/mu bootstrap/mu32.c
cc1: fatal error: bootstrap/mu32.c: No such file or directory
compilation terminated.
make: *** [Makefile:9: mu] Error 1
```

**Comment by nickmqb** [comment]
Thanks for the bug report! Looks like the bootstrap version of mu.c had become outdated, I've rebuilt the compiler using the interpreter and things should work now.

I'm not super familiar with makefiles, so I've just removed it for now, that way there is a single way to get things up and running as documented in getting_started.md.
