### ISSUE TITLE
Set up discord, slack or gitter

### ISSUE THREAD

**Issue by nickmqb** [nickmqb/muon#6]
As mentioned by wilberton in #5 .

**Comment by ghost** [comment]
Muon looks cool, and I'm interested in contributing. A discord channel would work well for getting everyone on the same page. Should I create one, or would the project owners like to do it?

**Comment by nickmqb** [comment]
I'm planning to set up the chat over the weekend. I was wondering what people's thoughts are regarding discord vs slack vs gitter?

**Comment by wilberton** [comment]
Personally I prefer discord, I just find it easier to use

**Comment by nickmqb** [comment]
Discord sounds good to me.

However, after some thought I've changed my mind on whether I should be the one to set up the discord. I'm already a bit too busy currently, so it's not a good idea for me to take on additional roles. While moderating a discord should not be too much work (at least initially), it does come with a responsibility to promptly deal with any spam, and to keep the discussion civil and on-topic, and I don't think I will have enough time to give it the level of attention that is required.

That said, if anyone from the community wants to take on this role and set up a "unofficial muon lang discord", I'd be happy to link to there from the README here, plus I might of course join the channel as a participant from time to time (can't make any promises though).

**Comment by ghost** [comment]
I'll set one up now, I have a little bit of experience. However, if the discord server will facilitate discussion among people contributing to Muon, I'd imagine that the owner not being particularly active on it may come across as a bit weird to some. Still, I hear what you are saying about the burden of responsibility. In fact, I'll probably get some others to help moderate it, even though i'm not that busy.

**Comment by ghost** [comment]
Ok, here it is:
[https://discord.gg/pbbhcvK](https://discord.gg/pbbhcvK)

I have made it clear the the server is not operated by the original authors. Feel free to put it in the README.

**Comment by nickmqb** [comment]
Nice, thanks for setting this up, I've added a section to the README.
