### ISSUE TITLE
debugging and line numbers

### ISSUE THREAD

**Issue by wilberton** [nickmqb/muon#8]
I have been trying to understand a bit more of the compiler code, and I thought it would be nice to be able to step through it in a debugger, so I added support for outputting #line info into the generated c files. At the moment it only adds them before each function, which is enough to be able to jump around the code in the debugger, step into functions and so on, but it quickly gets out of sync within functions. The next step would be adding a line number field to each Statement node, and then adding more #line directives whenever the generated C and the mu source get out of sync. I was wondering if this would be worth me doing, or if you've already thought about this and had a different plan for supporting debug info - I'm guessing that the LLVM backend will require adding file and line numbers to the IR?

**Comment by nickmqb** [comment]
Correct, the LLVM backend will emit source debug info (including line numbers), though I haven't gotten around to that yet. I was hoping to avoid adding stuff to the ast for this; ideally we would be able to get the source text range for each statement (e.g. using RangeFinder) and then map that to a line (perhaps using an additional data structure to facilitate that mapping, e.g. a `lineStart List<int>` which maps line N -> start source text index). So ideally we'd just need to change c_generator.mu; unless performance is not so good, then adding to the ast could be a way to mitigate that. Would also be nice to make emission of debug info optional, e.g. via something like an `emitDebugInfo bool` in GeneratorContext. Were you planning to work on this as a potential PR or just for yourself?

**Comment by wilberton** [comment]
Initially I was doing it just out of my own curiosity, but if I get it all working I can do a PR.
I'd be a little concerned about the performance implications of looking up line info for each statement during generation. Note you'd need the mapping to be the other way around, from source index -> line number. So either you store that for each index and use a potentially large amount of memory (with lots of redundancy), or you store just the start index for each line, and have a bit more work to do to find the line number given an index. Either way, I don't think that's ideal. 
What's your reasoning behind not wanting to add line numbers to the ast?

**Comment by wilberton** [comment]
Well I've implemented the simple version with adding line numbers to the statement nodes, but it still gets confused fairly easily if the mu code expands out to several lines of c code. I'm not sure that the #line directive actually supports what I want in order for it to work 100%. I rather think I might be abusing it beyond its limits.
Anyway, it works well enough for my initial use-case, which was to jump around the code of the compiler and follow what's going in order to just get my head around the architecture. It also helped me to track down a crash bug which I'll file as a separate issue.

**Comment by nickmqb** [comment]
Hey, glad this helped your initial use case, and thanks for filing that bug, I'll have a look. Which debugger were you using for stepping? It's good to know that #line has some rough edges in some debuggers. I propose leaving this issue where it is for now and coming back to it later -- I realize this needs a bit  more planning as to how I want to deal with mapping from code to source info. A minor pet peeve of mine is that some tools only deal with debug info at the line level, so things get a bit confusing when dealing with multiple statements per line; which isn't really an issue right now, but would be once we add things like lambda functions to Muon. I'd like to have a solution where we can map any ast node to line+column info, but which also performs well.

**Comment by nickmqb** [comment]
Closing, feel free to reopen if needed.
