### ISSUE TITLE
64bit support

### ISSUE THREAD

**Issue by wilberton** [nickmqb/muon#9]
I've totally ignored your instructions to install a 32bit tool chain, and I've encountered no issues at all so far - the compiler builds and runs fine with msvc, clang and gcc 64bit versions. What exactly is the issue with 64bit support?

**Comment by nickmqb** [comment]
You're right, it's pretty much done, there's a couple of TODOs remaining, mostly around handling ssize and usize correctly. Should be ready soon, I'll use this bug to track.
